### ISSUE TITLE
荣耀90手机5.12版本启动错误

### ISSUE THREAD

**Issue by Ainer1** [easybangumiorg/EasyBangumi#60]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.heyanle.easybangumi4/com.heyanle.easybangumi4.MainActivity}: java.lang.RuntimeException: Window couldn't find content container view
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4607)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4803)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:118)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:153)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:104)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:3064)
	at android.os.Handler.dispatchMessage(Handler.java:117)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:302)
	at android.app.ActivityThread.main(ActivityThread.java:9637)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:601)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1062)
Caused by: java.lang.RuntimeException: Window couldn't find content container view
	at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2947)
	at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:3039)
	at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2341)
	at androidx.activity.compose.c.a(SourceFile:1)
	at androidx.activity.compose.c.b(SourceFile:1)
	at com.heyanle.easybangumi4.MainActivity.onCreate(Unknown Source:32)
	at android.app.Activity.performCreate(Activity.java:9032)
	at android.app.Activity.performCreate(Activity.java:8991)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1470)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4589)
	... 12 more
java.lang.RuntimeException: Window couldn't find content container view
	at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2947)
	at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:3039)
	at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2341)
	at androidx.activity.compose.c.a(SourceFile:1)
	at androidx.activity.compose.c.b(SourceFile:1)
	at com.heyanle.easybangumi4.MainActivity.onCreate(Unknown Source:32)
	at android.app.Activity.performCreate(Activity.java:9032)
	at android.app.Activity.performCreate(Activity.java:8991)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1470)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4589)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4803)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:118)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:153)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:104)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:3064)
	at android.os.Handler.dispatchMessage(Handler.java:117)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:302)
	at android.app.ActivityThread.main(ActivityThread.java:9637)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:601)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1062)

**Comment by heyanLE** [comment]
5.2.1 会尝试修复（本来 5.2.0 就上的忘记push代码了
