### ISSUE TITLE
[5.4.2] 无法恢复备份，以及崩溃

### ISSUE THREAD

**Issue by TCOTC** [easybangumiorg/EasyBangumi#73]
标签丢失 #69 之后想看看能不能通过恢复备份找回，结果发现无法恢复备份，以及崩溃

然后我在手机里找到了这个名字的文件：[2024-06-10_00-44-58_1717951498087.easybangumi.backup.zip](https://github.com/user-attachments/files/16336523/2024-06-10_00-44-58_1717951498087.easybangumi.backup.zip)

https://github.com/user-attachments/assets/84182efe-ee92-407d-b6c4-c5e989418945

```
java.lang.IllegalArgumentException: Couldn't find meta-data for provider with authority com.heyanle.easybangumi4.fileProvider
	at androidx.core.content.b.getFileProviderPathsMetaData(Unknown Source:59)
	at androidx.core.content.b.g(SourceFile:1)
	at androidx.core.content.b.e(SourceFile:1)
	at androidx.core.content.b.getUriForFile(SourceFile:1)
	at com.heyanle.easybangumi4.storage.StorageController.share(Unknown Source:60)
	at com.heyanle.easybangumi4.ui.storage.restore.RestoreViewModel$share$1.invokeSuspend(Unknown Source:36)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(Unknown Source:130)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(SourceFile:3)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Unknown Source:5)
	at kotlinx.coroutines.CoroutineStart.invoke(SourceFile:2)
	at kotlinx.coroutines.AbstractCoroutine.start(Unknown Source:0)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Unknown Source:22)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:0)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Unknown Source:12)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:0)
	at com.heyanle.easybangumi4.ui.storage.restore.RestoreViewModel.share(Unknown Source:19)
	at com.heyanle.easybangumi4.ui.storage.restore.RestoreKt$Restore$10$1$1$2$2$1.invoke(SourceFile:2)
	at com.heyanle.easybangumi4.ui.storage.restore.RestoreKt$Restore$10$1$1$2$2$1.invoke(SourceFile:1)
	at androidx.compose.foundation.ClickablePointerInputNode$pointerInput$3.invoke-k-4lQ0M(Unknown Source:14)
	at androidx.compose.foundation.ClickablePointerInputNode$pointerInput$3.invoke(Unknown Source:6)
	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1.invokeSuspend(Unknown Source:186)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTaskKt.resume(Unknown Source:91)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(Unknown Source:51)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(Unknown Source:7)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(Unknown Source:33)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(Unknown Source:7)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(Unknown Source:10)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl$PointerEventHandlerCoroutine.o(SourceFile:1)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.P1(SourceFile:1)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.b0(SourceFile:1)
	at androidx.compose.foundation.AbstractClickablePointerInputNode.b0(SourceFile:1)
	at androidx.compose.foundation.AbstractClickableNode.b0(SourceFile:1)
	at androidx.compose.ui.input.pointer.l.f(SourceFile:1)
	at androidx.compose.ui.input.pointer.l.f(SourceFile:1)
	at androidx.compose.ui.input.pointer.l.f(SourceFile:1)
	at androidx.compose.ui.input.pointer.l.f(SourceFile:1)
	at androidx.compose.ui.input.pointer.l.f(SourceFile:1)
	at androidx.compose.ui.input.pointer.l.f(SourceFile:1)
	at androidx.compose.ui.input.pointer.l.f(SourceFile:1)
	at androidx.compose.ui.input.pointer.l.f(SourceFile:1)
	at androidx.compose.ui.input.pointer.l.f(SourceFile:1)
	at androidx.compose.ui.input.pointer.l.f(SourceFile:1)
	at androidx.compose.ui.input.pointer.l.f(SourceFile:1)
	at androidx.compose.ui.input.pointer.l.f(SourceFile:1)
	at androidx.compose.ui.input.pointer.m.f(SourceFile:1)
	at androidx.compose.ui.input.pointer.f.b(SourceFile:1)
	at androidx.compose.ui.input.pointer.B.a(SourceFile:1)
	at androidx.compose.ui.platform.AndroidComposeView.d1(SourceFile:1)
	at androidx.compose.ui.platform.AndroidComposeView.H0(SourceFile:1)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(Unknown Source:63)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3171)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2847)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3171)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2847)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3171)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2847)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3171)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2847)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:567)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1918)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4344)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:515)
	at android.view.View.dispatchPointerEvent(View.java:15398)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6984)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6741)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6192)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6254)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6215)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6385)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6223)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6442)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6196)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6254)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6215)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6223)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6196)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9385)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9336)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9296)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9532)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:281)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:349)
	at android.os.Looper.loopOnce(Looper.java:186)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8423)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@e49dc9b, Dispatchers.Main.immediate]
```

**Comment by AyalaKaguya** [comment]
恢复和备份问题统一下版本修
